#+begin_quote
Some notes about environment-related stuffes, in case I forget them in the future. They could also be useful for someone else.
#+end_quote

* Getting Start with Cider

With the necessary depedencies (clojure and nodejs, which you can get by using ~nix develop~, followed with ~npm -i~) installed.

Then in Emacs:

~cider-jack-in-cljs~ -> ~shadow-cljs~ -> ~shadow~ -> ~node-repl~

You can try to evaluate some code in ~playground.cljs~ after the environment is loaded.

Remeber, ~print~ doesn't work on async calls, use ~tap>~ for debugging purposes.

* Build Directly with NPM

#+begin_src sh
npm run build
#+end_src

* Update Dependencies in Nix

** Update JavaScript depedencies

Check https://nixos.org/manual/nixpkgs/stable/#javascript-buildNpmPackage

After doing ~npm update~

Use
#+BEGIN_SRC sh
prefetch-npm-deps package-lock.json
#+END_SRC
to get the value for ~npmDepsHash~ in flake.nix



** Update Clojure dependencies

After updating clojure dependencies :

#+BEGIN_SRC bash
nix run github:jlesquembre/clj-nix#deps-lock
#+END_SRC


* Nix-Related Commands

** Run the ~espoir~ Command

nix run . -- espoir

** Build the Project

#+begin_src sh
nix build .
#+end_src
Then check the result directory

* Publish Build to npm

After building the package with ~npm run release~

#+BEGIN_SRC bash
npm publish
#+END_SRC

